object Versions {
    const val gradlePlugin = "4.2.1"
    const val kotlinExtensions = "1.7.0"
    const val appCompat = "1.4.1"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val extJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val hilt = "2.40.5"
    const val room = "2.4.2"
    const val retrofit = "2.9.0"
    const val gson = "2.8.7"
    const val material = "1.6.0"
    const val kotlinCoroutines = "1.5.2"
    const val paging3 = "3.1.1"
    const val httpLogInterceptor = "4.9.3"
}